project:
  type: website
  output-dir: _output
  render:
    - index.qmd
  resources:
    - images/favicon.svg

format:
  revealjs:
    theme: night
    width: 1280
    height: 720
    slide-number: true
    # controls: true
    # controls-layout: bottom-right
    hash: true
    embed-resources: false
    css: talk.css
    chalkboard: true
    include-in-header:
      text: '<link rel="icon" type="image/svg+xml" href="images/favicon.svg">'
    footer: "Zombie-Radio · Austin Python Meetup · October 2026"
