project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: night
    width: 1280
    height: 720
    slide-number: true
    hash: true
    embed-resources: true
    footer: "Zombie-Radio · Austin Python Meetup · October 2026"
