"""Prepare the ambience for the app: tools/sounds/ambience.yaml's kept takes, encoded and measured into the fork.

Each kept take (a prompt's keep: seeds), generated by gen_ambience.py and copied into the datasets folder's round
folders, is encoded as MP3, mono, 96 kbps, as <tag>-<seed>.mp3 in the app's folder (the fork's checkout beside this
one: ../TalkWithZombies/Sounds/ambience). The clips ship with the app, so the folder is committed in the fork through a
pull request; never write into an installed client. Beside them, ambience.json holds each clip's file, tag, kind
(texture or spot), length, level and gain — the gain bringing the encoded clip's average level to loudness_dbfs, capped
so its peak stays at peak_cap_dbfs (a spot's boom stays under full scale) — and the prompt, model and seed it came
from. CREDITS.md says how they were made and that the project releases them as CC0. Which clips play, and any change
of a level by ear, is the story's to say (the fork's stories/<story>/ambience.yaml). Nothing is written without
--write; files of an earlier ambience.json that are no longer kept are removed, and nothing else in the folder is
touched.

  uv run python tools/sounds/prepare_ambience.py
  uv run python tools/sounds/prepare_ambience.py --write
"""

import argparse
import json
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

import yaml

from prepare_bed import measure

REPO = Path(__file__).resolve().parents[2]
MANIFEST = "ambience.json"
CREDITS = "CREDITS.md"
MODEL = "Stable Audio 3 Small-SFX"
LOUDNESS_DBFS = -20
PEAK_CAP_DBFS = -1
BITRATE = "96k"


def encode(src, dst):
    subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(src), "-ac", "1",
                    "-c:a", "libmp3lame", "-b:a", BITRATE, str(dst)], check=True)


def find_take(takes, tag, seed):
    found = sorted(takes.glob(f"*/{tag}/sa3-{seed}.wav"))
    if len(found) != 1:
        sys.exit(f"{tag} seed {seed}: {len(found)} takes found under {takes}, expected 1; nothing changed")
    return found[0]


def credits(rows):
    lines = ["# The ambience's clips: credits", "",
             "The world outside the lab, heard through the broadcast: the dead, the fighting, the people, the weather; and the "
             "sounds the story's events name (a helicopter, a phone, a typewriter), played when such an event is read.",
             f"Every clip was generated by the zombie-radio project with **{MODEL}** (Stability AI, "
             "https://huggingface.co/stabilityai/stable-audio-3-small-sfx), from the prompts below, and chosen by ear.",
             "", "**Licence: CC0 1.0** (https://creativecommons.org/publicdomain/zero/1.0/) — the project releases them",
             "into the public domain. The model's licence, the Stability AI Community License, gives the user the outputs:",
             "\"As between You and Stability AI, You own any outputs generated from the Models or Derivative Works to the",
             "extent permitted by applicable law\", and its \"Derivative Works\" \"do not include the output of any Model\".",
             "", "Encoded as MP3, mono, 96 kbps, by zombie-radio's `tools/sounds/prepare_ambience.py`; `ambience.json`",
             "beside this file lists them with their gains.", ""]
    for kind, title in (("texture", "Textures (continuous)"), ("spot", "Spots (single events)")):
        lines += [f"## {title}", ""]
        lines += [f"- `{r['file']}` — \"{r['prompt']}\" (seed {r['seed']})" for r in rows if r["kind"] == kind]
        lines.append("")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--config", type=Path, default=Path(__file__).resolve().parent / "ambience.yaml")
    p.add_argument("--takes", type=Path, default=REPO.parent / "zombie-radio-datasets" / "ambience")
    p.add_argument("--app", type=Path, default=REPO.parent / "TalkWithZombies" / "Sounds" / "ambience")
    p.add_argument("--write", action="store_true", help="encode the clips and write ambience.json; without it, a dry run")
    args = p.parse_args()

    prompts = yaml.safe_load(args.config.read_text(encoding="utf-8"))["prompts"]
    kept = [(x, seed, find_take(args.takes, x["tag"], seed)) for x in prompts for seed in x.get("keep", [])]
    print(f"takes {args.takes}\napp   {args.app}\nloudness {LOUDNESS_DBFS} dBFS, peak cap {PEAK_CAP_DBFS} dBFS, "
          f"{len(kept)} clips\n")

    rows = []
    with tempfile.TemporaryDirectory() as tmp:
        for x, seed, src in kept:
            name = f"{x['tag']}-{seed}.mp3"
            mp3 = Path(tmp) / name
            encode(src, mp3)
            m = measure(mp3)
            gain_db = min(LOUDNESS_DBFS - m["rms_dbfs"], PEAK_CAP_DBFS - m["peak_dbfs"])
            rows.append({"file": name, "tag": x["tag"], "kind": x["kind"], "seed": seed,
                         "seconds": round(m["seconds"], 1), "rms_dbfs": round(m["rms_dbfs"], 2),
                         "peak_dbfs": round(m["peak_dbfs"], 2), "gain_db": round(gain_db, 2),
                         "gain": round(10 ** (gain_db / 20), 4), "bytes": mp3.stat().st_size,
                         "prompt": x["prompt"], "model": MODEL, "licence": "CC0 1.0"})
            r = rows[-1]
            print(f"  {name:26} {r['kind']:7} {r['seconds']:5.1f} s  RMS {r['rms_dbfs']:6.1f}  peak {r['peak_dbfs']:5.1f}  "
                  f"gain {r['gain_db']:+6.1f} dB  {r['bytes'] // 1024:4d} KB")
            if args.write:
                args.app.mkdir(parents=True, exist_ok=True)
                (args.app / name).write_bytes(mp3.read_bytes())
    print(f"\n{sum(r['bytes'] for r in rows) / 1e6:.1f} MB, {sum(r['seconds'] for r in rows):.0f} s of sound")
    if not args.write:
        print("(dry run: nothing written; --write to write)")
        return

    old = args.app / MANIFEST
    if old.exists():
        for c in json.loads(old.read_text(encoding="utf-8"))["clips"]:
            if c["file"] not in {r["file"] for r in rows} and (args.app / c["file"]).exists():
                (args.app / c["file"]).unlink()
    manifest = {"prepared": datetime.now().isoformat(timespec="seconds"), "list": "zombie-radio tools/sounds/ambience.yaml",
                "loudness_dbfs": LOUDNESS_DBFS, "peak_cap_dbfs": PEAK_CAP_DBFS, "clips": rows}
    (args.app / MANIFEST).write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (args.app / CREDITS).write_text(credits(rows), encoding="utf-8")
    print(f"written: {len(rows)} clips, {MANIFEST}, {CREDITS}")


if __name__ == "__main__":
    main()
